FROM node:20.11.0

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

RUN apt-get install -y tzdata
RUN cp /usr/share/zoneinfo/America/Lima /etc/localtime

WORKDIR /usr/src/app

COPY package*.json ./

RUN rm -rf node_modules
RUN npm install

COPY . .

RUN npm run build

RUN mkdir dist/assets

EXPOSE 5041

CMD ["npm", "start", "PROD"]
